// Smart preprocess
pub const HIGH_CARDINALITY_THRESHOLD: usize = 50;
pub const SKEWNESS_THRESHOLD: f32 = 2.0;
pub const MISSING_INDICATOR_THRESHOLD: f32 = 0.05;
pub const PERMISSIVE_HIGH_CARDINALITY_THRESHOLD: usize = 100;
pub const PERMISSIVE_SKEWNESS_THRESHOLD: f32 = 3.0;
pub const PERMISSIVE_MISSING_INDICATOR_THRESHOLD: f32 = 0.1;
pub const STRICT_HIGH_CARDINALITY_THRESHOLD: usize = 25;
pub const STRICT_SKEWNESS_THRESHOLD: f32 = 1.5;
pub const STRICT_MISSING_INDICATOR_THRESHOLD: f32 = 0.02;

// Pipeline
pub const CMS_EPSILON: f64 = 0.001;
pub const CMS_CONFIDENCE: f64 = 0.99;
pub const MIN_CATEGORY_COUNT: u64 = 5;
pub const TARGET_ENCODING_SMOOTHING: f64 = 10.0;
