pub const DEFAULT_SPLIT_LAMBDA: f32 = 1.0;
pub const DEFAULT_SPLIT_MIN_SAMPLES_LEAF: u32 = 20;
pub const DEFAULT_SPLIT_MIN_HESSIAN_LEAF: f32 = 1.0;
pub const DEFAULT_SPLIT_MIN_GAIN: f32 = 0.0;
pub const DEFAULT_SPLIT_ENTROPY_WEIGHT: f32 = 0.0;
